Fix expired test certificates
It's the second time when expired test certificates break tests for me.
The current certs expired on 2021-04-28 08:50:35.

This happens because the test certificates are generated with validity
period of only 3 years. Let's change this to 100 years so that it
doesn't happen again.

This fixes test errors:
----
test_ssl_trust_rootca: test/test_util.c:551: expected <0> but was <120199>
test_ssl_certificate_chain_with_anchor: test/test_util.c:551: expected
<0> but was <120199>
test_ssl_certificate_chain_all_from_server: test/test_util.c:551:
expected <0> but was <120199>
test_ssl_no_servercert_callback_allok: test/test_util.c:551: An SSL
certificate related error occurred : expected <0> but was <120170>
test_ssl_large_response: test/test_util.c:551: An SSL certificate
related error occurred : expected <0> but was <120170>
test_ssl_large_request: test/test_util.c:551: An SSL certificate related
error occurred : expected <0> but was <120170>
test_ssl_client_certificate: test/test_ssl.c:1080: assert failed
test_ssl_revoked_server_cert: test/test_ssl.c:1284: expected <32> but
was <50>
test_setup_ssltunnel: test/test_util.c:551: expected <0> but was <120199>
test_ssltunnel_basic_auth: test/test_ssl.c:1477: expected <0> but was
<120170>
test_ssltunnel_basic_auth_server_has_keepalive_off:
test/test_ssl.c:1477: expected <0> but was <120170>
test_ssltunnel_basic_auth_proxy_has_keepalive_off: test/test_ssl.c:1477:
expected <0> but was <120170>
test_ssltunnel_basic_auth_proxy_close_conn_on_200resp:
test/test_ssl.c:1477: expected <0> but was <120170>
test_ssltunnel_basic_auth_2ndtry: test/test_ssl.c:1631: expected <0> but
was <120170>
test_ssltunnel_digest_auth: test/test_util.c:551: An SSL certificate
related error occurred : expected <0> but was <120170>
test_ssl_missing_client_certificate: test/test_ssl.c:1926: expected
<120172> but was <120170>
test_ssl_ocsp_response_error_and_override: test/test_util.c:551:
expected <0> but was <120199>
test_ssl_server_cert_with_san_and_empty_cb: test/test_util.c:551:
expected <0> but was <120199>
test_ssl_renegotiate: test/test_ssl.c:1882: expected <0> but was <120199>
test_ssl_ocsp_verify_response: test/test_ssl.c:2629: expected <0> but
was <120176>
test_ssl_ocsp_verify_response_no_nonce: test/test_ssl.c:2637: expected
<0> but was <120176>
test_ssl_ocsp_verify_response_ignore_missing_nonce:
test/test_ssl.c:2653: expected <0> but was <120176>
----

Patch by: Alexandr Miloslavskiy <alexandr.miloslavskiy{_AT_}syntevo.com>

* test/certs/create_certs.py
   Change 'VALID_DAYS' to 100 years.
   Change '13*365' parameters to default (100 years).
* test/certs:
   Regenerated using 'create_certs.py'
* test/test_ssl.c:
   (test_ssl_cert_certificate): Update certificate info.


git-svn-id: https://svn.apache.org/repos/asf/serf/trunk@1900591 13f79535-47bb-0310-9956-ffa450edef68